In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
import numpy as np
from sklearn.metrics import mean_squared_error as MSE
import xgboost as xg

In [4]:
df=pd.read_csv('measures_v2.csv')

In [5]:
X, y=df.iloc[:,:-1],df.iloc[:,-1]

In [27]:
X.head()

u_q    coolant  stator_winding       u_d  stator_tooth  motor_speed  \
0 -0.450682  18.805172       19.086670 -0.350055     18.293219     0.002866   
1 -0.325737  18.818571       19.092390 -0.305803     18.294807     0.000257   
2 -0.440864  18.828770       19.089380 -0.372503     18.294094     0.002355   
3 -0.327026  18.835567       19.083031 -0.316199     18.292541     0.006105   
4 -0.471150  18.857033       19.082525 -0.332272     18.291428     0.003133   

        i_d       i_q  stator_yoke    ambient    torque  profile_id  
0  0.004419  0.000328    18.316547  19.850691  0.187101          17  
1  0.000606 -0.000785    18.314955  19.850672  0.245417          17  
2  0.001290  0.000386    18.326307  19.850657  0.176615          17  
3  0.000026  0.002046    18.330833  19.850647  0.238303          17  
4 -0.064317  0.037184    18.326662  19.850639  0.208197          17

In [28]:
y.head()

0    24.554214
1    24.538078
2    24.544693
3    24.554018
4    24.565397
Name: pm, dtype: float64

In [6]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.3, random_state = 123)

In [7]:
xgb_r = xg.XGBRegressor(objective ='reg:linear', n_estimators = 10, seed = 123)

In [8]:
xgb_r.fit(train_X, train_y)

[14:50:34] WARNING: C:/Users/administrator/workspace/xgboost-win64_release_1.6.0/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=10, n_jobs=0,
             num_parallel_tree=1, objective='reg:linear', predictor='auto',
             random_state=123, reg_alpha=0, ...)

In [9]:
pred = xgb_r.predict(test_X)

In [10]:
rmse = np.sqrt(MSE(test_y, pred))

In [11]:
print("RMSE : % f" %(rmse))

RMSE :  4.874544


In [12]:
print(rmse)

4.874543934089797


In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()
model = scaler.fit(X)
scaled_data = model.transform(X)

In [15]:
print(scaled_data)

[[-1.24036638 -0.66658658 -1.52351282 ... -2.26183357 -0.4697415
  -0.73806883]
 [-1.23748512 -0.66592586 -1.52332011 ... -2.2618434  -0.46898148
  -0.73806883]
 [-1.24013998 -0.66542296 -1.52342151 ... -2.26185126 -0.46987815
  -0.73806883]
 ...
 [-0.07255486 -0.38846954  0.91865436 ...  0.84200917 -2.62461009
   1.17732663]
 [-0.06596371 -0.38519697  0.92040839 ...  0.84458053 -2.59239941
   1.17732663]
 [-0.05763958 -0.38285207  0.92153495 ...  0.846423   -2.55320461
   1.17732663]]


In [16]:
train_X, test_X, train_y, test_y = train_test_split(scaled_data, y, test_size = 0.3, random_state = 123)

In [17]:
xgb_r = xg.XGBRegressor(objective ='reg:linear', n_estimators = 10, seed = 123)
xgb_r.fit(train_X, train_y)

[14:50:52] WARNING: C:/Users/administrator/workspace/xgboost-win64_release_1.6.0/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=10, n_jobs=0,
             num_parallel_tree=1, objective='reg:linear', predictor='auto',
             random_state=123, reg_alpha=0, ...)

In [18]:
pred = xgb_r.predict(test_X)
rmse = np.sqrt(MSE(test_y, pred))
print("RMSE : % f" %(rmse))

RMSE :  4.820868


In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler = MinMaxScaler()
model=scaler.fit(X)
scaled_data=model.transform(X)

In [21]:
print(scaled_data)

[[0.15689681 0.05741649 0.00407938 ... 0.34610384 0.48604373 0.18987342]
 [0.15768599 0.05756904 0.00412597 ... 0.3461027  0.48615865 0.18987342]
 [0.15695882 0.05768515 0.00410146 ... 0.34610178 0.48602307 0.18987342]
 ...
 [0.4767616  0.12162747 0.5945033  ... 0.70862626 0.16022563 0.79746835]
 [0.47856693 0.12238304 0.59492736 ... 0.70892659 0.16509592 0.79746835]
 [0.48084692 0.12292442 0.59519972 ... 0.70914178 0.17102221 0.79746835]]


In [22]:
train_X, test_X, train_y, test_y = train_test_split(scaled_data, y, test_size = 0.3, random_state = 123)

In [23]:
xgb_r = xg.XGBRegressor(objective ='reg:linear', n_estimators = 10, seed = 123)
xgb_r.fit(train_X, train_y)

[14:51:09] WARNING: C:/Users/administrator/workspace/xgboost-win64_release_1.6.0/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=10, n_jobs=0,
             num_parallel_tree=1, objective='reg:linear', predictor='auto',
             random_state=123, reg_alpha=0, ...)

In [24]:
pred = xgb_r.predict(test_X)
rmse = np.sqrt(MSE(test_y, pred))
print("RMSE : % f" %(rmse))

RMSE :  4.866876


In [25]:
from sklearn.metrics import r2_score

In [26]:
r2_score(test_y,pred)

0.9407916407702377

In [45]:
from sklearn.preprocessing import LabelEncoder

In [46]:
le = LabelEncoder()
train_y = le.fit_transform(train_y)

In [31]:
pip install hyperopt

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy in c:\users\akvg2\anaconda3\lib\site-packages (from hyperopt) (1.21.5)



In [32]:
from hyperopt import STATUS_OK, Trials, fmin, hp, tpe

In [33]:
space={'max_depth': hp.quniform("max_depth", 3, 18, 1),
        'gamma': hp.uniform ('gamma', 1,9),
        'reg_alpha' : hp.quniform('reg_alpha', 40,180,1),
        'reg_lambda' : hp.uniform('reg_lambda', 0,1),
        'colsample_bytree' : hp.uniform('colsample_bytree', 0.5,1),
        'min_child_weight' : hp.quniform('min_child_weight', 0, 10, 1),
        'n_estimators': 180,
        'seed': 0
    }

In [47]:
def objective(space):
    clf=xg.XGBClassifier(
                    n_estimators =space['n_estimators'], max_depth = int(space['max_depth']), gamma = space['gamma'],
                    reg_alpha = int(space['reg_alpha']),min_child_weight=int(space['min_child_weight']),
                    colsample_bytree=int(space['colsample_bytree']))
    
    evaluation = [( train_X, train_y), ( test_X, test_y)]
    
    clf.fit(train_X, train_y,
            eval_set=evaluation, eval_metric="auc",
            early_stopping_rounds=10,verbose=False)
    

    pred = clf.predict(test_X)
    accuracy = accuracy_score(y_test, pred>0.5)
    print ("SCORE:", accuracy)
    return {'loss': -accuracy, 'status': STATUS_OK }